apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
  labels: 
    name: nginx-service
spec: 
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 80
  # label keys and values that must match in order to receive traffic for this service
  selector: 
    name: nginx
